### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [Bill13579/rustdsp#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Libraries](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md) - [DSPs](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#dsps-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/Bill13579/rustdsp)
(generate url: https://flat.badgen.net/github/license/Bill13579/rustdsp)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration (and therefore evolution) between developers of listed projects.

Thanks in advance.

**Comment by Bill13579** [comment]
Fixed. The badge should show up correctly now after the cache clears, thanks for placing it on HyMPS! I think the categorization you have right now is pretty good already, I found it quite fun to scroll through it.. although admittedly I was slightly confused at the Bundles and Singles classification haha.

**Comment by MarcoRavich** [comment]
Thanks for the timely fix!

As you can see (above too) the badge is now generated correctly.

The Effects page is in "restructuration mode" (your observation pushed us to adopt icons for stating the pages' status in their top-right corner) 'cause we are merging other stuff into it and we must rework the navigation menu.

At the moment we decided to sort resources alphabetically (as you can see in DAWs and Libraries pages) but we recently decided to introduce a multi-level sorting.
Projects will be grouped+sorted with a different criterias (by this "sorting chain": Section > Subsection > Language > License > Alphabetical) and will therefore showed in a slightly different but - hopefully - more effective way.

Check out the 1st test in the Generic subsection of the Editors page:

https://github.com/forart/HyMPS/blob/main/Aeditors.md#generic-

Do you think this new approach could better foster collaboration between devs ?

Thanks again and, if you like/need, let us know (by replying to [our discussions](https://github.com/forart/HyMPS/discussions)) how we can support listed projects.

Last but not least, Happy New Year !

**Comment by Bill13579** [comment]
Yeah, sorting by programming language could foster collaboration (although do take this with a grain of salt)! It's generally harder for projects to help each other out when they're in totally different languages. Realtime stuff like audio doesn't play well with loads of FFI across langauges. I do think though that some ecosystems here are quite young. In general audio processing is not a field with heavy open-source (yet!) in my opinion, and I think your efforts are commendable. I'll keep an eye out for your project and page, hope it goes well, and yeah, happy 2023!
